### PR TITLE
Update Wheeler-Kiladis POD with verified observations

### PR DESCRIPTION
**Pull request by tsjackson-noaa**
Re-create pull request NOAA-GFDL/MDTF-diagnostics#45 to pull from @bitterbark 's `develop` branch (bitterbark/MDTF-diagnostics@2fdf1021d5e52b6a2b3489a104cbbe305ce9cbd8).

### CODE REVIEW

**Comment by tsjackson-noaa** [comment]
Hi @bitterbark ,
Thanks for the updates, and sorry for all the redundant notifications.
 
Does [fieldlist_OBS_WK.jsonc](https://github.com/bitterbark/MDTF-diagnostics/blob/develop/src/fieldlist_OBS_WK.jsonc) correspond to variable name conventions for an NCAR model configuration we should support? If this file contains variable names for the new obs data, that's not necessary -- since the framework doesn't touch the obs data, variable names in those files can be hard-coded in the POD code.

**Comment by bitterbark** [comment]
1) Pull request from branch
Just to check: you moved this to my branch apparently, so I don't have to change anything in that regard?
Overall the  https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/CONTRIBUTING.md documentation is very helpful, it just needs the part in https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#creating-the-pull-request about switching branches from the webpage. (Since my local repository & commits were all on the develop branch, I figured they would go in there!)

2) Regarding  fieldlist_OBS_WK.jsonc, it shows how to run the MDTF to produce the obs figures. I can see how it shouldn't be included in the src/ directory, so I will move it to the 'supporting materials' as the "script" to go with the data used to recreate the obs plots.

3) Posting obs data
Unfortunately I ran into a problem with one of the observational products so there will be a delay on finalizing. The code should be okay but of course there is a chance of changes. Shall I finalize the commit/pull, and update later, or leave this open?

**Comment by tsjackson-noaa** [comment]
1. Yes -- the current request is to merge the current state of your `develop` branch into NOAA-GFDL's `pod/Wheeler_Kiladis` branch (shown at the top of this page). This will use the current state of your `develop` branch whenever the merge is actually performed. I'll update the CONTRIBUTING instructions accordingly.

2. Thanks for the clarification; agree that this should be with the POD's code.

3. My preference would be to leave this request open until the obs data is sorted out. I'm guessing new obs has the same filenames as old obs, so new code + old obs wouldn't produce an error (or produce misleading output, since obs is a set of plots for comparison), but treating code + obs data as a single unit should be less error-prone.

**Comment by bitterbark** [comment]
I committed changes to my local copy but when I tried to push them to my
fork of develop (which I understand would automatically go into the pull
request), it says there is a conflict because someone else has made changes
to my fork. Is this from you (Tom) making the pull request from my fork to
the right branch? If so, do I do a normal 'git pull upstream develop' or
???

% git push
To github.com:bitterbark/MDTF-diagnostics.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to
        'git@github.com:bitterbark/MDTF-diagnostics.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

On Wed, Sep 30, 2020 at 8:55 AM Thomas Jackson <notifications@github.com>
wrote:
>
> Yes -- the current request is to merge the current state of your develop
branch into NOAA-GFDL's pod/Wheeler_Kiladis branch (shown at the top of
this page). This will use the current state of your develop branch whenever
the merge is actually performed. I'll update the CONTRIBUTING instructions
accordingly.
>
> Thanks for the clarification; agree that this should be with the POD's
code.
>
> My preference would be to leave this request open until the obs data is
sorted out. I'm guessing new obs has the same filenames as old obs, so new
code + old obs wouldn't produce an error (or produce misleading output,
since obs is a set of plots for comparison), but treating code + obs data
as a single unit should be less error-prone.

**Comment by bitterbark** [comment]
Meanwhile, 
1) obs_data/Wheeler-Kiladis figures are updated in ftp://ftp.cgd.ucar.edu/archive/mdtf/MDTF_v2.1.a.obs_data.tar
(linked to MDTF_v2.1.a.20201001.obs_data.tar ). I can change this name to v3.0_beta whenever you're ready to update links.

2) The full observational data that can be used along with provided {fieldlist,input}_OBS_WK.jsonc (in diagnostics/Wheeler-Kiladis) to re-create the figures provided in obs_data/Wheeler-Kiladis are available for anyone to download
 ftp://ftp.cgd.ucar.edu/archive/mdtf/obs_Wheeler-Kiladis.20201001.tar

Let me know if I've forgotten an established protocol for these supporting data.

**Comment by bitterbark** [comment]
Tom, I am ready to do the next pull request with changes to MJO_suite. I did it on top of these changes, so I don't know if I should wait for this to be resolved, or just do them all together from scratch on a new pull request. Advice?

**Comment by tsjackson-noaa** [comment]
Hi @bitterbark -- sorry I missed the notification on your questions above.

1) re: pushing local changes: I'm not sure how your develop branches would have gotten out of sync -- the pull request wouldn't have affected this, and at any rate neither I nor the NOAA-GFDL account can write to your stuff. The develop branch on GitHub's copy of your repo has its last commit on [Sep 24th](https://github.com/bitterbark/MDTF-diagnostics/commits/develop). To list the commits your GitHub repo has that your local repo doesn't have, try
```
> git log develop..develop@{origin}
```
It should be safe to pull the stuff GitHub has that the local copy doesn't via `git pull origin`, after which `git push origin` should work without the error.

2) Thanks for updating the obs data and the tarballs! Just to check, the HTML template circa Sep 24th uses TRMM data for precip:
https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/7c121caa5e7a8d9c71ea276bbe7badea7cdf53e8/diagnostics/Wheeler_Kiladis/Wheeler_Kiladis.html#L126-L144
but the new obs data plots use NCEP for everything -- just want to confirm that that's the plan.

3) I'll make a new `pod/MJO_suite` branch for those updates, and you should submit a separate pull request -- that'll keep stuff from the different PODs separate and organized. Hopefully the process should go smoother.

**Comment by bitterbark** [comment]
Forgive my awkwardness with git, it takes a lot of work for me to see what is necessary. I did 'git pull origin' and solved some conflicts, then 'git push origin' to hopefully get the rest of my commits to this branch. Am testing it in the pod now; not clear to me how to do that before the push so hopefully it will work.

**Comment by bitterbark** [comment]
Unfortunately something doesn't work from mdtf.py. I'm finding this setup prohibitively complicated (with the pull request created by Tom, which only included a subset of my commits, and merged with what appears to be a new branch on the main site). I'm going to try to do it cleanly, where I can control what is going on, and will make a new pull request.

**Comment by bitterbark** [comment]
@tsjackson-noaa, I'm running into the same problem just with a clean version of upstream develop. 
It is coming from the change 
OLD  import cli
NEW from src import cli

Is there something I have to change in my setup to make this work? Otherwise I get the following error:
Traceback (most recent call last):
  File "/home/bundy/mdtf/MDTF-diagnostics/src/mdtf.py", line 27, in
  <module>
    from src import cli
ImportError: No module named src

**Comment by jkrasting** [comment]
@bitterbark - I did a clean checkout of your branch and I did not hit this error.  (Instead I hit #65, which I think happens later than your issue)

Have you tried (in a new directory) to clone your repository and re-checkout the `develop` branch?

**Comment by bitterbark** [comment]
I did a clean checkout of the upstream/develop branch (none of my mods) and
got the same error.  I re-ran ./src/conda/conda_env_setup.sh. But it didn't
help.

I can see that the code change came in May
<https://github.com/NOAA-GFDL/MDTF-diagnostics/commit/74a5385e7ef06bda0c968ac16519d32008db6cfa#diff-5e30fbff1c732cb0cfc93ad2f70a269c77cf79858ea120fe47147b8703b3a5a3>(!).
So clearly it's working for others. I can redo the clone and install from
the start, just was hoping to be able to use the merge tools (and
understand what is going on with the setup!)

Thanks for your help, John.

**Comment by jkrasting** [comment]
Can you post your command sequence, @bitterbark? We can try your exact set of commands to see if we can reproduce things.  If you can start with the "git clone" that would be helpful. Thanks!

**Comment by bitterbark** [comment]
I found the issue. Although I had updated the code (pull upstream/develop), I hadn't re-run conda_env_setup.sh. In retrospect it seems obvious, but a few caveats 1) if it wasn't obvious to me, it won't be obvious to all pod developers,  2) even once I figured out to do it, it took a careful re-reading of the install documentation to figure out what to do and 3) since this changes the conda env, now my other branches (not yet updated to upstream develop) are no longer compatable with the MDTF_base environment.  Maybe you have an easy answer that I'm missing, otherwise hoepfully we have time to discuss this in the meeting today.

**Comment by tsjackson-noaa** [comment]
Everything looks good -- merged into [pod/Wheeler_Kiladis](https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/pod/Wheeler_Kiladis); is included as part of the POD dev branch merges in [v3 alpha 3](https://github.com/tsjackson-noaa/MDTF-diagnostics/tree/feature/v3alpha3-pods-only). Closing this PR.

**Pull request merged**
