### PR TITLE
First pull request for the tropical pacific sea level POD

### PR DESCRIPTION
**Pull request by chiaweh2**
Hi lead team,

This is my first attempt for the pull request for POD tropical_pacific_sea_level. I have many parts that I have not been able to make it work with the framework. Currently, the POD is working fine when execute in my local server with the Conda env set to _MDTF_python3_base through "python pod.py" (meaning execute through python directly not incorporate with the framework). However, I am not able to successfully make it work by doing ./mdtf -f src/default_cesm2.jsonc (the .jsonc I created). I am guessing there is something wrong in the setting.jsonc or default_cesm2.jsonc. I also create a fieldlist file for OMIP_CESM. I remember you suggested all questions can be posted through the GitHub for better tracking. So I hope I am not misunderstanding by doing a pull request with questions. Should I just posted this question in issues?

### CODE REVIEW

**Comment by wrongkindofdoctor** [comment]
@chiaweh2 You can post questions in the issues, (and submit PRs in *draft* mode if you are not ready for a full review) in the future. Can you respond with the error message(s) you are getting when you try to run your POD with the framework?

**Comment by chiaweh2** [comment]
@wrongkindofdoctor sorry to post this at the wrong place. Should I maybe remove this pull request and repost in issue? The error message is posted below when I execute ` ./mdtf -f src/default_cesm2.jsonc`. I create the `default_cesm2.jsonc` to run this POD.

`- _unittest: false
  CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
Traceback (most recent call last):
  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 319, in <module>
    mdtf = MDTFFramework(code_root, defaults_rel_path)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 60, in __init__
    self._framework_init(code_root, defaults_rel_path)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 82, in _framework_init
    self.parse_mdtf_args(cli_obj, config)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 114, in parse_mdtf_args
    self.parse_paths(cli_obj, config)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 207, in parse_paths
    config.paths.parse(cli_obj.config, cli_obj.custom_types.get('path', []))
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util_mdtf.py", line 44, in parse
    self[key] = self._init_path(key, d, env=env)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util_mdtf.py", line 64, in _init_path
    util.coerce_from_iter(d[key]), root_path=self.CODE_ROOT, env=env
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util.py", line 427, in resolve_path
    path = os.path.expanduser(path) # resolve '~' to home dir
  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by wrongkindofdoctor** [comment]
Thanks, chiaweh2. This helps a lot. And, yes, please move this to an issue. It will be easier to manage it separately from the PR, and we can reference it in the future if needed.

**Comment by chiaweh2** [comment]
Thanks @wrongkindofdoctor. I have open a new issue and reference this PR.

**Comment by jkrasting** [comment]
Closing - moved discussion to #73.  @chiaweh2 - you can reopen a PR when you are ready to merge.

**Pull request closed without merging**
