### PR TITLE
Feature/add temp extremes distshape

### PR DESCRIPTION
**Pull request by tsjackson-noaa**
**Description**
Continuation of PR #29, now that level extraction has been implemented (see discussion #120). PR includes commits made as part of PR #265.

Outstanding issues:
- `Moments` and `ShiftRatio` model plots raise range errors. Plot range appears to be set to 180 E longitude, possibly due to an error in shifting longitude range of the data.
- Obs data figures are provided as hard-coded .pngs, instead of plotting "predigested data." Obs data `CircComps` plots only provided for Yellowknife/DJF and Rennes/JJA, instead of for all cities/seasons plotted in `FreqDists` and specifiable through the settings file.

**How Has This Been Tested?**
POD has been tested on published CMIP6 data from GFDL-ESM4. 

**Checklist:**
- [X] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [X] My branch is up-to-date with the NOAA-GFDL develop branch, and all merge conflicts are resolved
- [ ] The script are written in Python 3.6 or above (preferred; required if funded by a CPO grant), NCL, or R
- [ ] All of my scripts are in the diagnostics/[POD short name] subdirectory, and include a main_driver script, template html, and settings.jsonc file
- [ ] I have made corresponding changes to the documentation in the POD's doc/ subdirectory
- [ ] If applicable, I've added a .yml file to src/conda, and my environment builds with `conda_env_setup.sh` 
- [ ] I have added any necessary data to input_data/obs_data/[pod short name] and/or input_data/model/[pod short name]
- [ ] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not contain hard-coded file or directory paths
- [ ] I have provided the code to generate digested data files from raw data files
- [ ] Each digested data file generated by the script contains numerical data (no figures), and is 3 GB or less in size
- [ ] The repository contains no extra test scripts or data files

### CODE REVIEW

**Review by wrongkindofdoctor — APPROVED** [review]

**Review by jkrasting — DISMISSED** [review]

**Comment by tsjackson-noaa** [comment]
Successfully debugged axis range problem in 3a3d6d9, thanks to advice from @jkrasting. After the above commits, claim that code is working correctly (see results in `/home/Thomas.Jackson/mdtf_out/MDTF_ESM4_historical_D1_1996_2009.v4`, and compare with supplied docs [PDF](https://github.com/tsjackson-noaa/MDTF-diagnostics/blob/8420716c0b9ea8cc30059014e693e67b5ea5c14d/diagnostics/temp_extremes_distshape/temp_extremes_distshape_Documentation.pdf)).

**Review by wrongkindofdoctor — DISMISSED** [review]

**Comment by jkrasting** [comment]
@tsjackson-noaa, I created synthetic data at 20º, 10º, and 5º resolutions.  Can you see what is the coarsest resolution, if any, we can get this POD to run on?

The test data are in `/net2/jpk/mdtf_test_data/temp_ext_test_data`

**Comment by tsj5** [comment]
Response to [jkasting's question](https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/264#issuecomment-898008717) about synthetic data -- reply was sent over email, but is quoted again here:

"The good news is that temp_extremes_distshape runs without errors on even the 20deg data -- no errors or warnings are logged, and the plots look reasonable once you remember the input data are gaussian noises. Outputs of the POD on the synthetic data are shared in MDTF_* directories in the Google Drive folder linked to above.

POD runtime statistics (on my home laptop) -- all of these were for 10 years of daily synthetic data.
5 deg: 62.50s user 5.32s system 205% cpu 33.019 total
10 deg: 52.35s user 3.13s system 238% cpu 23.228 total
20 deg: 48.58s user 2.14s system 263% cpu 19.226 total"

**Comment by tsjackson-noaa** [comment]
Closing PR as code has been merged into `/develop` with PR #273.

**Pull request closed without merging**
