### PR TITLE
Add development cheatsheet to docs

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
**Description**
I've added a development cheatsheet with brief instructions on file locations and variable creation/reference in response to discussion #228 

**Checklist:**
- [x] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [ ] The script are written in Python 3.6 or above (preferred; required if funded by a CPO grant), NCL, or R
- [ ] All of my scripts are in the diagnostics/ subdirectory, and include a main_driver script template html, and settings.jsonc
- [ ] The main_driver script header has all of the information in the POD documentation, excluding the "More about this diagnostic" section
- [ ] The POD directory and html template have the same short name as my POD
- [ ] The html template has a 1-paragraph synopsis of the POD and links to the main documentation
- [ ] If applicable, I've added a .yml file to src/conda, and my environment builds with conda_env_setup.sh 
- [ ] The POD scripts do not access the internet or networked resources
- [ ] I have commented the code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation in the POD's doc/ subdirectory
- [ ] I have created the directory input_data/obs_data/[pod short name]
- [ ] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not contain hard-coded file or directory paths
- [ ] I have added information about the raw data files to the documentation
- [ ] I have provided the code to generate digested data files from raw data files
- [ ] Each digested data file generated by the script contains numerical data (no figures), and is 3 GB or less in size
- [x] The repository contains no extra test scripts or data files
- [x] My branch is up-to-date with the NOAA-GFDL develop branch, and all merge conflicts are resolved

### CODE REVIEW

**Comment by yihungkuo** [comment]
@wrongkindofdoctor A few comments.

1. Currently this cheat sheet is "buried" deep in the package, and impossible to find without the knowledge of its existence. We should consider coordinated changes being made to e.g., the beginning of README.md and the the front page of the documentation website so that people can easily access it. People having to look for a cheat sheet kind of defeats its purpose in my opinion. Also, the cheat sheet related updates should go into the official develop branch soon since POD developers are now working on implementation.

2. I feel that the current cheat sheet content isn't comprehensive enough and can be more specific. As an example, here's an older version of the [POD Development Checklist](https://github.com/yihungkuo/MDTF-diagnostics/blob/feature/docs/doc/sphinx/dev_checklist.rst) which I think would be more helpful for POD developers. @bitterbark @ahmedfiaz @cmartinezvil What do you think?

3. Some of the POD developers may benefit from a short summarizing section for conda command/environment, especially for those who are not familiar with Python.

**Comment by wrongkindofdoctor** [comment]
@yihungkuo I can add the checklist to the TOC for the main docs, and link it to the README.md file once it is finalized. Linking the developer checklist is also not an issue, but there is not a reason to copy/paste the same information in multiple places. Similar arguments apply for 3., since the documentation summarizes the options for the `conda_env_install.sh` script, and the anaconda site is the appropriate source conda-specific commands that users may want more information for. If something is not clear, we need feedback from the community at large as to what information they need rather than speculation.

That said, all of this linking to a cheatsheet is effectively creating an abbreviated TOC for the main documentation, which seems to point to a larger issue with the documentation UI/UX. What I am getting from this and prior discussions about the documentation is that the issue is not necessarily with a lack of information, but with ease of navigation. One thing I've noticed on the [readthedocs site](https://mdtf-diagnostics.readthedocs.io/en/latest/index.html) is that the side bar with the table of contents is not comprehensive. That is, it includes links to primary headings, but does not display sub(sub)headings until you click the main link, which requires opening extra tabs/windows to make backwards navigation easier. The splash page displays the full TOC, but this disappears after clicking the link, so you have to hit the browser "back" button to return to the prior page. 

It seems like it would be more productive to modify the documentation [conf.py](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/doc/conf.py) file to add some navigation features rather than investing an inordinate amount of time in a reference document that re-publishes the same information. Note that I am not opposed to having a cheatsheet. However, keep in mind that cheatsheets are typically a page's worth of tips or commonly-used commands (e.g., the [anaconda cheatsheet](https://ugoproto.github.io/ugo_py_doc/img/scipy_cs/conda-cheatsheeta.png)), not a slightly shorter version of the primary documentation.

@yihungkuo @bitterbark @thomas-robinson @jkrasting Have I described the main issue(s) with the documentation, or am I missing something? Would it be useful to solicit feedback from the community on improving the documentation navigation?

**Comment by yihungkuo** [comment]
@wrongkindofdoctor Some quick thoughts. I totally agree with you that this is more about documentation navigation, and if the documentation UI/UX or TOC can be greatly improved, we don't need to keep separate copies of information in multiple places (nor  should we). However, I am not sure which approach would be easier: coming up with a reasonably good documentation UI/UX/TOC or keeping a separate cheat sheet. Also, I don't think redundancy is necessarily a bad thing. Providing and maintaining a separate cheat sheet would require additional effort. But as the project transitions to the next phase, we can probably expect more continuity regarding the framework code and documentation, and more emphasis on maintenance. So this would likely be a one-time effort, and require minimal updates in the future (?).

Regarding 3. @xiananjiang had read the document section for conda, but still encountered problems. I don't think he's alone since the targeted readers of the documentation would be postdoc/grad/undergrad, likely unfamiliar with Python/conda. I think there are certain aspects of the current documentation regarding conda/framework environment can be improved/expanded further. 

We don't need to rush to conclusion here. The POD teams are now starting to implement their PODs. Based on the experience from phase 1, some of the teams will keep working during their no cost extension. We will see how helpful the current documentation is, gather feedback, and update when needed.

**Comment by bitterbark** [comment]
I agree that we don't need to come to a conclusion, but we should stand something up soon. Having  developers  using the cheat sheet and making suggestions for what would be more helpful would be very useful (for them to have some guidance implementing pods and for us to develop the documentation for the next phase).

I also agree that it seems to be an organizational issue rather than informational, and I absolutely agree we shouldn't repeat information (otherwise it is more work to change things and very likely to lead to contradictory information). 

My experience was having to jump all around to find what I wanted to know so I wrote the first draft as a kind of **interface with the documentation specifically for pod developers.**  I think this is best accomplished with much more concise list and links. 
My preference is to have an ordered list of simple phrases, where each is followed by a + or 'click for more' paragraph (if the formating permits it to remain hidden) Within those paragraphs we link to the actual documentation. If we feel we must include detailed documentation in this cheatsheet, it is a sign we need to put it somewhere else. (For example, how different languages access environment variables).

 I would suggest a reorganization of this information with a single To Do list, separated into 5 sections:
1) Prepare for implementation
- run the unmodified MDTF making sure your conda, dir structure etc. is set up
- modify the conda env to work for your pod
- name your pod, make a directory and move your code to the correct location
- cp your obs_data to the right dir
- cp your model data to the right dir (if necessary)
2) Link POD code into framework
- modify input.jscon (note 1, below) to call your pod
- modify pod's driver.py to interface with your code
- modify pod's settings.json to specifiy variables that will be provided by framework
- modify code to use env vars provided by the framework  
a. input files (note 2)
b. working files
c. output figures
- modify html files to point to figure names (note 3)
3) Documentation 
4) Testing
5) Submit through GH

Notes:
1) I still think that calling it default_tests.jsonc makes it look like a testing file, rather than an input file. Why not just input.jsonc? 
2) In the version I'm running, the framework re-writes the model data into a file in WK_DIR, and that's how the pod is suspposed to access it, not through DATADIR at all. Unless this is changed, we should make this clear. Otherwise it is really confusing (Also this is where to have the note about save_nc, as when this intermediate file is deleted, the user has no chance of figuring out the error).
3)The section about output figures is grayed out in the view I can see of it, can we make it look more relevant? Also, I don't understand the wording concerning the PS/PNG/matplotlib problem. If I understand correctly, may I suggest:
Output figure locations: 
- PNG files should be placed directly in $WK_DIR/obs/ and $WK_DIR/model/  
- If a POD chooses to save vector-format figures, they should be written into the $WK_DIR/obs/PS and $WK_DIR/model/PS
directories. Files in these locations will be converted by the framework to PNG, so use those names in the html file.
- If a POD uses matplotlib, it is recommended to write as EPS instead of PS because of potential bugs

Also:
- I don't think we should invite frustration by saying "You should have no problem" with anything!
- Wherever we refer to a directory in the documentation we should use the env vars (for instance, replace 'output directory' with WK_DIR. If this could always be a link to the master doc about env vars, we only have to explain it there.

Finally, I apologize for not re-engaging earlier on this and I understand if it is too late to make suggestions.

**Comment by cmartinezvil** [comment]
Hi all,
Thank you @yihungkuo  for putting forward this issue, I'm one of the people who brought forward the need for a cheatsheet. I wholeheartedly agree with @bitterbark message, the phrase "My experience was having to jump all around to find what I wanted to know" really captures my experience. As has been said, this is totally an organizational issue rather than informational —there is all you need to know if you know where to find it, where to find it is the problem. A cheatsheet structured as a "to do list" as @bitterbark suggested would be super helpful, at least for me.

Thank you!

**Comment by jkrasting** [comment]
Yes, I echo the importance of getting something to the POD developers ASAP as far as cheat sheet goes.  @wrongkindofdoctor - what do you think about rolling out what we have here or if it is still premature?

**Comment by yihungkuo** [comment]
@bitterbark Those are great suggestions! I think the format you proposed will work. Maybe we should come up with a to-do list/cheat sheet including slightly more detailed steps (with the lab instructions for an undergrad course in mind) and use it as an alternative format of TOC and/or coordinate documentation around the to-do list.

**Comment by xiananjiang** [comment]
I would like to share a little bit of my experience with the "conda" installation since @yihungkuo mentioned. I totally had no experience with conda before - not quite understood what conda is for. So I tried to install conda following the manual. As I found that Centos includes "conda" by itself, I installed conda by using "yum install conda" using "root". I then downloaded MDTF package and put it under my home directory, and run "conda_env_setup" also using "root" and "/usr/bin(I guess?) for the "conda_root" and with "--env_dir" using default location (actually I did know where it was located). The installation was fine. After that I used ./mdtf under the MDTF package, and tried to run the package successfully. But it was realized later with the help from @yihungkuo that the python version and libraries that I used were actually installed by myself instead of "conda" based on the MDTF package. As suggested by @yihungkuo, I then reinstalled "miniconda" package as suggested in the manuscript under my home directory using my login instead of "root", and specified "--end_dir" explicitly. After that everything becomes much easier to be configured. Also, it could be helpful to provide a little more detailed instruction on how to activate the conda "envs", for example "_MDTF_python3_base".  Many thanks, Yi-Hung, for the help!

**Comment by wrongkindofdoctor** [comment]
@yihungkuo @jkrasting @bitterbark @cmartinezvil Thanks for the feedback. Since it sounds like people are on board with @bitterbark's list format, and want this ASAP, I'll go ahead and redo the file so it is ready for review today. I'll leave it in its current location (can always move it later), and make sure to link to it from the beginning of the README file.

**Comment by bitterbark** [comment]
Thanks, Jess!

**Review by tsjackson-noaa — DISMISSED** [review]

**Review by tsjackson-noaa — APPROVED** [review]

**Pull request merged**
