### PR TITLE
Add multirun support: framework mods and example_multicase POD

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
**Description**
This is the initial draft PR for the alpha version of the multi-run implementation of the framework. The modifications extend the existing routines to preprocess data from multiple model simulations (e.g., ensemble members, or runs from the different time periods in the same simulations), which are designated as "cases" in the configuration file and framework. Environment variables and simulation metadata are assigned to attributes in each case object. The case objects are, in turn, assigned to a pod object. Information from the pod object is passed to the runtime manager. 

Case environment variables are written to file called `case_info.yml` in the pod run directory (e.g., /wkdir/example_multicase/case_info.yml). The example_multicase POD reads this file into a dictionary to obtain information about the environment variables assigned to the data on a per-case basis. A sample [case_info.yaml](https://github.com/wrongkindofdoctor/MDTF-diagnostics/blob/add_multirun_support/diagnostics/example_multicase/case_info.yaml) file is provided for the configuration in the [example_multicase configuration file](https://github.com/wrongkindofdoctor/MDTF-diagnostics/blob/add_multirun_support/diagnostics/example_multicase/multirun_config_template.jsonc)

To generate the synthetic cmip data described in the multirun_config_template:
```
mamba env create --force -q -f ./src/conda/_env_synthetic_data.yml
conda activate _MDTF_synthetic_data
pip install mdtf-test-data
mkdir mdtf_test_data && cd mdtf_test_data
mdtf_synthetic.py -c CMIP --startyear 1980 --nyears 5
mdtf_synthetic.py -c CMIP --startyear 1985 --nyears 5
```

Associated issue #309

**How Has This Been Tested?**
Initial testing has been done with synthetic data generated for two different 5-year time periods using the CMIP format and python 3.7

**Checklist:**
- [x] I have reviewed my own code to ensure that if follows the [POD development guidelines](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_guidelines.html)
- [x] My branch is up-to-date with the NOAA-GFDL main branch, and all merge conflicts are resolved
- [x] The scripts are written in Python 3.7 or above (preferred; required if funded by a CPO grant), NCL, or R
- [x] All of my scripts are in the diagnostics/[POD short name] subdirectory, and include a main_driver script, template html, and settings.jsonc file
- [x] I have made corresponding changes to the documentation in the POD's doc/ subdirectory
- [x] I have requested that the framework developers add packages required by my POD to the python3, NCL, or R environment yaml file if necessary, and my environment builds with `conda_env_setup.sh` 
- [x] I have added any necessary data to input_data/obs_data/[pod short name] and/or input_data/model/[pod short name]
- [x] My code is portable; it uses [MDTF environment variables](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_envvars.html), and does not contain hard-coded file or directory paths
- [x] I have provided the code to generate digested data files from raw data files
- [x] Each digested data file generated by the script contains numerical data (no figures), and is 3 GB or less in size
- [x] The repository contains no extra test scripts or data files

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
Screen Shot 2022-10-13 at 10 18 12 AM

Yay. I was able to run a sample test-case on synthetic CMIP data.  The instructions to test this PR may need to be refined for other users, all steps from start to finish with links to quick start would help. The input json could use env variables and not assume certain paths to help repeat the steps and improve user testing experience. I ran into issues when testing with GFDL synthetic data instructions in PR, because the synthetic data directory did not hold any tas/t_ref files in my test. The error messages could be improved, but its for another cut of the code.

 
In general, a newer version of the input json for multi-case with GFDL and CMIP [synthetic] example, would help. Once @bitterbark tests this PR, an NCAR example added to the [example_multicase configuration file](https://github.com/wrongkindofdoctor/MDTF-diagnostics/blob/add_multirun_support/diagnostics/example_multicase/multirun_config_template.jsonc) config would be useful. 

Have we discussed testing with one multi-case and one single-case POD with the same configuration?

**Comment by wrongkindofdoctor** [comment]
@aradhakrishnanGFDL Thanks! I will clean up the sample json config file and add some documentation for the final PR. We will need another small example case modified to ingest environment variables from the yaml to test the single-case/multirun mode POD.

**Comment by aradhakrishnanGFDL** [comment]
> @aradhakrishnanGFDL Thanks! I will clean up the sample json config file and add some documentation for the final PR. We will need another small example case modified to ingest environment variables from the yaml to test the single-case/multirun mode POD. Also, I realized that the synthetic data generation instructions incorrectly specified `-c GFDL instead of -c CMIP`. I edited the original comment.

Good, -c CMIP worked for me right away -- and that clarifies that the GFDL synthetic was not expected to work for this particular POD configuration.

**Comment by aradhakrishnanGFDL** [comment]
@wrongkindofdoctor The framework expects OBS_DATA_ROOT even if the POD does not use OBS datasets. Is this worth a new low-priority issue?

**Comment by wrongkindofdoctor** [comment]
> > @aradhakrishnanGFDL Thanks! I will clean up the sample json config file and add some documentation for the final PR. We will need another small example case modified to ingest environment variables from the yaml to test the single-case/multirun mode POD. Also, I realized that the synthetic data generation instructions incorrectly specified `-c GFDL instead of -c CMIP`. I edited the original comment.
> 
> Good, -c CMIP worked for me right away -- and that clarifies that the GFDL synthetic was not expected to work for this particular POD configuration.



> @wrongkindofdoctor The framework expects OBS_DATA_ROOT even if the POD does not use OBS datasets. Is this worth a new low-priority issue?

Yes, that's probably a good call.

**Comment by bitterbark** [comment]
This [ran on the NCAR computers](https://www2.cgd.ucar.edu/cms/bundy/Projects/diagnostics/mdtf/mdtf_figures/outdir.PR407/example_multicase/example_multicase.html) using the synthetic data (thanks for the flawless instructions to make it).

I like how little changes between the multirun_config.jsonc and the previous config file. 
Also it is great that the example_multicase.py is so simple and clear.

Do you want a few typos corrected in the instructions/web page or should that wait until later?
Next week I can try to run on NCAR data. 

Later, modifying the blocking pod to use these capabilities will be a tougher test.
But I think this is very much on the right track.
Let me know if there's something else I need to do (I haven't been an official reviewer before).

**Pull request merged**
