### PR TITLE
Removed trailing line at end of README.md

### PR DESCRIPTION
**Pull request by jkrasting**

### CODE REVIEW

**Review by tsjackson-noaa — APPROVED** [review]
Dummy comment, to see where it gets put in the paper trail

**Comment by jkrasting** [comment]
I think it might have been smart enough to know not to ask me to approve my own PR!  @tsjackson-noaa, @wrongkindofdoctor - could either of you make a dummy PR to see if that is indeed the case?

**Comment by tsjackson-noaa** [comment]
> I think it might have been smart enough to know not to ask me to approve my own PR! @tsjackson-noaa, @wrongkindofdoctor - could either of you make a dummy PR to see if that is indeed the case?

I haven't been able to find any info confirming or denying this, but it's a decent guess -- for the record #60 is listed as requiring two reviewers as well.

**Comment by tsjackson-noaa** [comment]
Closing this PR, since it was just for testing purposes.

**Pull request closed without merging**
