### PR TITLE
Container

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
**Description**
Container build in GitHub actions workflow, an accompanying Dockerfile also pushed. 

**How Has This Been Tested?**
Tested at GFDL using podman. Local test instructions passed to @jtmims. Works on synthetic data and example POD. Works partially on forcing feedback, but replicates non-container workflow. Open to more tests and documentation.

### CODE REVIEW

**Comment by jtmims** [comment]
Great news @aradhakrishnanGFDL! I was able to pull the docker package from the github repository and launch on my windows machine. Inside, I was able to run the example_multicase POD on some synthetic data, and it ran and plotted. It's functional! It's really cools seeing a container working on some data! I did have some trouble with tracking down micromamba/conda env related paths, but that is something that could be cleared up with some docs.

**Comment by aradhakrishnanGFDL** [comment]
@wrongkindofdoctor do you prefer merging this into main, or maintain a separate container branch until things seem to be working as expected? There is a CI workflow that builds a docker image and pushes to GitHub.io registry. It does not seem harmful to have it merge into main, except tests for the container as part of CI are not in right now.

**Comment by aradhakrishnanGFDL** [comment]
@jtmims @wrongkindofdoctor I tested the workflow with another PR that pushes to a container branch. 

Here is the actions workflow -

https://github.com/NOAA-GFDL/MDTF-diagnostics/actions/runs/10891122710/job/30221357884

@jtmims you can now use this for the docs instead my ghrc.io pointers. Hope this helps.

https://github.com/noaa-gfdl/MDTF-diagnostics/pkgs/container/mdtf-diagnostics

**Comment by aradhakrishnanGFDL** [comment]
> @wrongkindofdoctor do you prefer merging this into main, or maintain a separate container branch until things seem to be working as expected? There is a CI workflow that builds a docker image and pushes to GitHub.io registry. It does not seem harmful to have it merge into main, except tests for the container as part of CI are not in right now.

I have a container branch created. You can delete it as you see fit. I am okay with this PR being merged into main, in any case. I leave it to you and @jtmims.

**Review by wrongkindofdoctor — APPROVED** [review]

**Pull request merged**
