### PR TITLE
Feature/my new code

### PR DESCRIPTION
**Pull request by github-demo08540**
Here's the code for my new POD. You should add it to GFDL's repo because I'm the coolest person ever.

### CODE REVIEW

**Comment by tsjackson-noaa** [comment]
Thanks! When I try to run your code, it makes my computer burst into flames. Could you fix this bug first?

**Comment by github-demo08540** [comment]
OK, I'll fix things with my powers of coolness.

**Comment by github-demo08540** [comment]
I made a new commit with the bug fix. Do things work now?

**Comment by tsjackson-noaa** [comment]
Yes! We are humbled by your scientific genius. Your request has been accepted!

**Comment by tsjackson-noaa** [comment]
Closing since this was just done for a live demo.

**Pull request closed without merging**
